### ISSUE TITLE
Blank window

### ISSUE THREAD

**Issue by mpkuse** [alexflint/image-marks#2]
Hi,
Thanks for providing this tool. 

I was trying to run your tool. I clone your repo and in it put 2 images. I try to run it on Ubuntu 16.04 python 2.7 as : 

`python correspondence_tool.py im1.jpg im2.jpg`

I just see a blank screen. Help appreciated !

**Comment by alexflint** [comment]
My guess would be that either (1) the wx api has changed and is no longer compatible with this code, (2) the images could not be decoded, or (3) a python version issue. This code was written around 5 years ago and I haven't tried running it for several years. The whole program is just a few hundred lines of code though, so it should be easy to debug. Do let me know if you are able to track down the problem.
